version: "3"

tasks:
  build:
    cmds:
      - pip install -e ".[dev]"
      - hatch env create
  mypy:
    cmds:
      - mypy openimagingdatamodel
  ruff_lint:
    cmds:
      - ruff check openimagingdatamodel
  ruff_format:
    cmds:
      - ruff format openimagingdatamodel
  lint:
    cmds:
      - task ruff_lint
      - task mypy
      - task ruff_format
  test:
    cmds:
      - PYTHONPATH=. pytest
  check:
    cmds:
      - task lint
      - task test