# generated by datamodel-codegen:
#   filename:  cdeset_schema_example.json
#   timestamp: 2024-12-04T16:58:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class SetVersion(BaseModel):
    number: int
    date: str


class CurrentStatus(BaseModel):
    date: str
    status: str


class StatusHistoryItem(BaseModel):
    date: str
    status: str


class Reference(BaseModel):
    citation: str
    doi_url: str
    pubmed_id: str


class Organization(BaseModel):
    name: str
    abbreviation: str
    role: str


class Person(BaseModel):
    name: str
    role: str
    email: str
    orcid_id: Optional[str] = None
    affiliation: Optional[str] = None


class Contributors(BaseModel):
    organizations: List[Organization]
    people: List[Person]


class Specialty(BaseModel):
    name: str
    abbreviation: str


class Modality(BaseModel):
    code: str


class IndexCodes(BaseModel):
    system: str
    code: str
    display: str


class BodyPart(BaseModel):
    name: str
    index_codes: IndexCodes


class ElementVersion(BaseModel):
    number: int
    date: str


class CurrentStatus1(BaseModel):
    status: str
    date: str


class IndexCode(BaseModel):
    system: str
    code: str
    display: str
    url: str


class BodyPart1(BaseModel):
    name: str
    index_codes: IndexCodes


class Organization1(BaseModel):
    name: str
    abbreviation: str


class Contributors1(BaseModel):
    organizations: List[Organization1]
    people: List[Person]


class IntegerValue(BaseModel):
    min: int
    max: Optional[int] = None
    step: int
    unit: str


class IndexCode1(BaseModel):
    system: str
    code: str
    url: str
    display: str


class Value(BaseModel):
    code: str
    value: str
    name: str
    definition: str
    index_codes: Optional[List[IndexCode1]] = None


class ValueSet(BaseModel):
    min_cardinality: int
    max_cardinality: int
    values: List[Value]


class Element(BaseModel):
    id: str
    parent_set: str
    name: str
    definition: str
    question: str
    schema_version: str
    element_version: ElementVersion
    current_status: CurrentStatus1
    index_codes: Optional[List[IndexCode]] = None
    body_parts: Optional[List[BodyPart1]] = None
    modalities: Optional[List[Modality]] = None
    contributors: Contributors1
    integer_value: Optional[IntegerValue] = None
    value_set: Optional[ValueSet] = None


class Model(BaseModel):
    id: str
    name: str
    description: str
    set_version: SetVersion
    schema_version: str
    current_status: CurrentStatus
    status_history: List[StatusHistoryItem]
    references: List[Reference]
    contributors: Contributors
    specialties: List[Specialty]
    modalities: List[Modality]
    body_parts: List[BodyPart]
    elements: List[Element]
